name: Windows CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 6"
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Webview2 SDK
        run: |
          mkdir libs\webview2
          nuget.exe install Microsoft.Web.Webview2 -Version 1.0.1150.38 -OutputDirectory libs\webview2
          copy libs\webview2\microsoft.web.webview2.1.0.1150.38\build\native\include\*.h ext\
      - name: Install crystal land dependencies
        run: shards install
      - name: Compile library
        run: make
      - name: Run tests
        run: crystal spec
